class FoodSuggestion {
  final String name;
  final int caloriesPerUnit;

  FoodSuggestion({required this.name, required this.caloriesPerUnit});
}

final Map<String, List<FoodSuggestion>> categorizedFoodSuggestions = {
  'Breakfast': [
    FoodSuggestion(name: 'Idli', caloriesPerUnit: 39),
    FoodSuggestion(name: 'Dosa (Plain)', caloriesPerUnit: 133),
    FoodSuggestion(name: 'Masala Dosa', caloriesPerUnit: 168),
    FoodSuggestion(name: 'Rava Dosa', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Set Dosa', caloriesPerUnit: 130),
    FoodSuggestion(name: 'Uttapam', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Pesarattu', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Appam', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Idiyappam', caloriesPerUnit: 160),
    FoodSuggestion(name: 'Upma', caloriesPerUnit: 192),
    FoodSuggestion(name: 'Rava Upma', caloriesPerUnit: 192),
    FoodSuggestion(name: 'Sevai Upma', caloriesPerUnit: 165),
    FoodSuggestion(name: 'Vermicelli Upma', caloriesPerUnit: 170),
    FoodSuggestion(name: 'Pongal', caloriesPerUnit: 205),
    FoodSuggestion(name: 'Poha', caloriesPerUnit: 158),
    FoodSuggestion(name: 'Kanda Poha', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Thalipeeth', caloriesPerUnit: 130),
    FoodSuggestion(name: 'Akki Roti', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Ragi Roti', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Ragi Mudde', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Paratha (Plain)', caloriesPerUnit: 126),
    FoodSuggestion(name: 'Aloo Paratha', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Gobi Paratha', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Paneer Paratha', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Thepla', caloriesPerUnit: 100),
    FoodSuggestion(name: 'Puri', caloriesPerUnit: 101),
    FoodSuggestion(name: 'Bhatura', caloriesPerUnit: 295),
    FoodSuggestion(name: 'Mysore Bonda', caloriesPerUnit: 140),
    FoodSuggestion(name: 'Medu Vada', caloriesPerUnit: 97),
    FoodSuggestion(name: 'Masala Vada', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Bonda', caloriesPerUnit: 140),
    FoodSuggestion(name: 'Dhokla', caloriesPerUnit: 152),
    FoodSuggestion(name: 'Kachori', caloriesPerUnit: 190),
    FoodSuggestion(name: 'Misal Pav', caloriesPerUnit: 289),
    FoodSuggestion(name: 'Bread Pakora', caloriesPerUnit: 223),
    FoodSuggestion(name: 'Onion Pakora', caloriesPerUnit: 190),
    FoodSuggestion(name: 'Sabudana Khichdi', caloriesPerUnit: 224),
    FoodSuggestion(name: 'Rava Kesari', caloriesPerUnit: 184),
    FoodSuggestion(name: 'Banana', caloriesPerUnit: 89),
    FoodSuggestion(name: 'Egg Bhurji', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Omelette', caloriesPerUnit: 154),
    FoodSuggestion(name: 'Egg Curry', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Pancakes (Plain)', caloriesPerUnit: 227),
    FoodSuggestion(name: 'Pancakes with Syrup', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Waffles', caloriesPerUnit: 218),
    FoodSuggestion(name: 'French Toast', caloriesPerUnit: 226),
    FoodSuggestion(name: 'Scrambled Eggs', caloriesPerUnit: 148),
    FoodSuggestion(name: 'Boiled Eggs', caloriesPerUnit: 68),
    FoodSuggestion(name: 'Bacon', caloriesPerUnit: 42),
    FoodSuggestion(name: 'Sausage', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Hash Browns', caloriesPerUnit: 143),
    FoodSuggestion(name: 'Croissant', caloriesPerUnit: 231),
    FoodSuggestion(name: 'Bagel (Plain)', caloriesPerUnit: 245),
    FoodSuggestion(name: 'Toast with Butter', caloriesPerUnit: 171),
    FoodSuggestion(name: 'Granola with Milk', caloriesPerUnit: 215),
    FoodSuggestion(name: 'Oatmeal', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Smoothie (Fruit)', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Yogurt Parfait', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Muffin (Blueberry)', caloriesPerUnit: 265),
    FoodSuggestion(name: 'Donut (Glazed)', caloriesPerUnit: 260),
    FoodSuggestion(name: 'Avocado Toast', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Caprese Sandwich', caloriesPerUnit: 310),
    FoodSuggestion(name: 'Breakfast Burrito', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Frittata', caloriesPerUnit: 196),
    FoodSuggestion(name: 'Quiche', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Cereal with Milk', caloriesPerUnit: 190),
    FoodSuggestion(name: 'Espresso', caloriesPerUnit: 3),
    FoodSuggestion(name: 'Cappuccino', caloriesPerUnit: 80),
    FoodSuggestion(name: 'Latte', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Black Coffee', caloriesPerUnit: 2),
    FoodSuggestion(name: 'Hot Chocolate', caloriesPerUnit: 200),
  ],
  'Lunch': [
    FoodSuggestion(name: 'Brown Rice', caloriesPerUnit: 111),
    FoodSuggestion(name: 'Red Rice', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Black Rice', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Quinoa (Cooked)', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Foxtail Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Barnyard Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Little Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Kodo Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Sorghum (Jowar)', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Finger Millet (Ragi)', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Plain Rice', caloriesPerUnit: 130),
    FoodSuggestion(name: 'Jeera Rice', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Ghee Rice', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Curd Rice', caloriesPerUnit: 165),
    FoodSuggestion(name: 'Veg Pulao', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Paneer Pulao', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Chicken Pulao', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Veg Biryani', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Chicken Biryani', caloriesPerUnit: 290),
    FoodSuggestion(name: 'Mutton Biryani', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Egg Biryani', caloriesPerUnit: 275),
    FoodSuggestion(name: 'Lemon Rice', caloriesPerUnit: 160),
    FoodSuggestion(name: 'Tamarind Rice', caloriesPerUnit: 170),
    FoodSuggestion(name: 'Tomato Rice', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Fried Rice (Veg)', caloriesPerUnit: 215),
    FoodSuggestion(name: 'Fried Rice (Chicken)', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Fried Rice (Egg)', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Chapati', caloriesPerUnit: 71),
    FoodSuggestion(name: 'Tandoori Roti', caloriesPerUnit: 102),
    FoodSuggestion(name: 'Butter Naan', caloriesPerUnit: 262),
    FoodSuggestion(name: 'Garlic Naan', caloriesPerUnit: 270),
    FoodSuggestion(name: 'Plain Paratha', caloriesPerUnit: 126),
    FoodSuggestion(name: 'Aloo Paratha', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Paneer Paratha', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Lachha Paratha', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Missi Roti', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Puri', caloriesPerUnit: 101),
    FoodSuggestion(name: 'Dal Tadka', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Dal Makhani', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Chole', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Rajma', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Paneer Butter Masala', caloriesPerUnit: 330),
    FoodSuggestion(name: 'Palak Paneer', caloriesPerUnit: 280),
    FoodSuggestion(name: 'Kadai Paneer', caloriesPerUnit: 290),
    FoodSuggestion(name: 'Matar Paneer', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Baingan Bharta (Brinjal Curry)', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Bhindi Masala', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Ivy Gourd Curry', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Aloo Gobi', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Mixed Vegetable Curry', caloriesPerUnit: 190),
    FoodSuggestion(name: 'Vegetable Korma', caloriesPerUnit: 220),
    FoodSuggestion(name: 'Methi Aloo', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Spinach Dal', caloriesPerUnit: 160),
    FoodSuggestion(name: 'Drumstick Sambar', caloriesPerUnit: 190),
    FoodSuggestion(name: 'Chicken Curry', caloriesPerUnit: 290),
    FoodSuggestion(name: 'Butter Chicken', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Chicken Korma', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Mutton Curry', caloriesPerUnit: 340),
    FoodSuggestion(name: 'Fish Curry', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Prawn Curry', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Egg Curry', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Veggie & Egg Curry', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Keema Matar', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Green Salad', caloriesPerUnit: 40),
    FoodSuggestion(name: 'Onion & Cucumber Salad', caloriesPerUnit: 30),
    FoodSuggestion(name: 'Sprout Salad', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Fruit Salad', caloriesPerUnit: 95),
    FoodSuggestion(name: 'Raita', caloriesPerUnit: 80),
    FoodSuggestion(name: 'Papad', caloriesPerUnit: 26),
    FoodSuggestion(name: 'Pickle', caloriesPerUnit: 20),
    FoodSuggestion(name: 'Veg Thali', caloriesPerUnit: 750),
    FoodSuggestion(name: 'Non-Veg Thali', caloriesPerUnit: 950),
    FoodSuggestion(name: 'South Indian Thali', caloriesPerUnit: 800),
    FoodSuggestion(name: 'North Indian Thali', caloriesPerUnit: 850),
    FoodSuggestion(name: 'Veg Burger', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Chicken Burger', caloriesPerUnit: 420),
    FoodSuggestion(name: 'Cheeseburger', caloriesPerUnit: 480),
    FoodSuggestion(name: 'French Fries', caloriesPerUnit: 312),
    FoodSuggestion(name: 'Veg Pizza (Regular Slice)', caloriesPerUnit: 285),
    FoodSuggestion(name: 'Cheese Pizza (Regular Slice)', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Pepperoni Pizza (Regular Slice)', caloriesPerUnit: 313),
    FoodSuggestion(name: 'Pasta Alfredo', caloriesPerUnit: 380),
    FoodSuggestion(name: 'Pasta Arrabbiata', caloriesPerUnit: 330),
    FoodSuggestion(name: 'Lasagna (Veg)', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Lasagna (Chicken)', caloriesPerUnit: 400),
    FoodSuggestion(name: 'Grilled Cheese Sandwich', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Club Sandwich', caloriesPerUnit: 400),
    FoodSuggestion(name: 'Caesar Salad', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Grilled Chicken Breast', caloriesPerUnit: 284),
    FoodSuggestion(name: 'Fish and Chips', caloriesPerUnit: 585),
    FoodSuggestion(name: 'Shawarma Roll', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Falafel Wrap', caloriesPerUnit: 300),
  ],
  'Snack': [
    FoodSuggestion(name: 'Maggi Noodles', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Veg Ramen Bowl', caloriesPerUnit: 400),
    FoodSuggestion(name: 'Chicken Ramen Bowl', caloriesPerUnit: 450),
    FoodSuggestion(name: 'Hakka Noodles Cup', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Cup Noodles (Veg)', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Cup Noodles (Chicken)', caloriesPerUnit: 340),
    FoodSuggestion(name: 'Pani Puri (6 pcs)', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Bhel Puri', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Sev Puri (6 pcs)', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Dahi Puri (6 pcs)', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Samosa', caloriesPerUnit: 130),
    FoodSuggestion(name: 'Kachori', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Bread Pakora', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Mirchi Bajji', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Onion Pakoda', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Aloo Bonda', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Punugulu', caloriesPerUnit: 220),
    FoodSuggestion(name: 'Mysore Bonda', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Medu Vada', caloriesPerUnit: 97),
    FoodSuggestion(name: 'Masala Vada', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Batata Vada', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Potato Chips (Small Pack)', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Potato Chips (Large Pack)', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Nachos with Cheese Dip', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Popcorn (Salted, 1 cup)', caloriesPerUnit: 55),
    FoodSuggestion(name: 'Popcorn (Butter, 1 cup)', caloriesPerUnit: 78),
    FoodSuggestion(name: 'Masala Papad', caloriesPerUnit: 60),
    FoodSuggestion(name: 'Veg Sandwich', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Grilled Cheese Sandwich', caloriesPerUnit: 330),
    FoodSuggestion(name: 'Chicken Sandwich', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Club Sandwich', caloriesPerUnit: 400),
    FoodSuggestion(name: 'Paneer Tikka Sandwich', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Apple', caloriesPerUnit: 52),
    FoodSuggestion(name: 'Orange', caloriesPerUnit: 47),
    FoodSuggestion(name: 'Grapes (100g)', caloriesPerUnit: 69),
    FoodSuggestion(name: 'Watermelon (100g)', caloriesPerUnit: 30),
    FoodSuggestion(name: 'Papaya (100g)', caloriesPerUnit: 43),
    FoodSuggestion(name: 'Mango (100g)', caloriesPerUnit: 60),
    FoodSuggestion(name: 'Guava (100g)', caloriesPerUnit: 68),
    FoodSuggestion(name: 'Pineapple (100g)', caloriesPerUnit: 50),
    FoodSuggestion(name: 'Mixed Fruit Bowl', caloriesPerUnit: 85),
    FoodSuggestion(name: 'Gulab Jamun (1 pc)', caloriesPerUnit: 125),
    FoodSuggestion(name: 'Rasgulla (1 pc)', caloriesPerUnit: 106),
    FoodSuggestion(name: 'Jalebi (50g)', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Kaju Katli (1 pc)', caloriesPerUnit: 57),
    FoodSuggestion(name: 'Ladoo (Boondi, 1 pc)', caloriesPerUnit: 186),
    FoodSuggestion(name: 'Halwa (Carrot, 100g)', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Payasam (100g)', caloriesPerUnit: 220),
    FoodSuggestion(name: 'Chocolate Brownie', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Cheesecake Slice', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Ice Cream (Vanilla Scoop)', caloriesPerUnit: 137),
    FoodSuggestion(name: 'Ice Cream (Chocolate Scoop)', caloriesPerUnit: 143),
    FoodSuggestion(name: 'Ice Cream Sundae', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Waffles with Syrup', caloriesPerUnit: 310),
    FoodSuggestion(name: 'Pancakes with Syrup', caloriesPerUnit: 280),
    FoodSuggestion(name: 'Donut (Glazed)', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Muffin (Chocolate)', caloriesPerUnit: 370),
    FoodSuggestion(name: 'Apple Pie Slice', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Tiramisu Slice', caloriesPerUnit: 330),


  ],
  'Dinner': [
    FoodSuggestion(name: 'Brown Rice', caloriesPerUnit: 111),
    FoodSuggestion(name: 'Red Rice', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Black Rice', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Quinoa (Cooked)', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Foxtail Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Barnyard Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Little Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Kodo Millet', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Sorghum (Jowar)', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Finger Millet (Ragi)', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Steamed Rice', caloriesPerUnit: 130),
    FoodSuggestion(name: 'Jeera Rice', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Ghee Rice', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Curd Rice', caloriesPerUnit: 165),
    FoodSuggestion(name: 'Veg Pulao', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Paneer Pulao', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Chicken Pulao', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Veg Biryani', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Chicken Biryani', caloriesPerUnit: 290),
    FoodSuggestion(name: 'Mutton Biryani', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Egg Biryani', caloriesPerUnit: 275),
    FoodSuggestion(name: 'Fried Rice (Veg)', caloriesPerUnit: 215),
    FoodSuggestion(name: 'Fried Rice (Egg)', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Fried Rice (Chicken)', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Chapati/Phulka/Roti', caloriesPerUnit: 71),
    FoodSuggestion(name: 'Tandoori Roti', caloriesPerUnit: 102),
    FoodSuggestion(name: 'Butter Naan', caloriesPerUnit: 262),
    FoodSuggestion(name: 'Garlic Naan', caloriesPerUnit: 270),
    FoodSuggestion(name: 'Plain Paratha', caloriesPerUnit: 126),
    FoodSuggestion(name: 'Lachha Paratha', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Dal Tadka', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Dal Makhani', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Palak Paneer', caloriesPerUnit: 280),
    FoodSuggestion(name: 'Paneer Butter Masala', caloriesPerUnit: 330),
    FoodSuggestion(name: 'Kadai Paneer', caloriesPerUnit: 290),
    FoodSuggestion(name: 'Matar Paneer', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Baingan Bharta', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Bhindi Masala', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Aloo Gobi', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Methi Malai Matar', caloriesPerUnit: 270),
    FoodSuggestion(name: 'Vegetable Korma', caloriesPerUnit: 220),
    FoodSuggestion(name: 'Drumstick Sambar', caloriesPerUnit: 190),
    FoodSuggestion(name: 'Butter Chicken', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Chicken Curry', caloriesPerUnit: 290),
    FoodSuggestion(name: 'Chicken Chettinad', caloriesPerUnit: 310),
    FoodSuggestion(name: 'Chicken Korma', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Mutton Rogan Josh', caloriesPerUnit: 360),
    FoodSuggestion(name: 'Mutton Curry', caloriesPerUnit: 340),
    FoodSuggestion(name: 'Fish Curry', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Prawn Curry', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Egg Curry', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Veggie & Egg Curry', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Keema Matar', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Veg Manchurian (Dry)', caloriesPerUnit: 220),
    FoodSuggestion(name: 'Veg Manchurian (Gravy)', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Chicken Manchurian', caloriesPerUnit: 270),
    FoodSuggestion(name: 'Paneer Chilli Dry', caloriesPerUnit: 260),
    FoodSuggestion(name: 'Paneer Chilli Gravy', caloriesPerUnit: 280),
    FoodSuggestion(name: 'Gobi Manchurian', caloriesPerUnit: 240),
    FoodSuggestion(name: 'Chicken Lollipop', caloriesPerUnit: 210),
    FoodSuggestion(name: 'Hakka Noodles (Veg)', caloriesPerUnit: 220),
    FoodSuggestion(name: 'Hakka Noodles (Chicken)', caloriesPerUnit: 250),
    FoodSuggestion(name: 'Schezwan Noodles', caloriesPerUnit: 260),
    FoodSuggestion(name: 'Schezwan Fried Rice', caloriesPerUnit: 270),
    FoodSuggestion(name: 'Spring Rolls', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Grilled Salmon', caloriesPerUnit: 367),
    FoodSuggestion(name: 'Grilled Chicken Breast', caloriesPerUnit: 284),
    FoodSuggestion(name: 'Steak (Beef)', caloriesPerUnit: 679),
    FoodSuggestion(name: 'Lamb Chops', caloriesPerUnit: 340),
    FoodSuggestion(name: 'Roast Turkey', caloriesPerUnit: 189),
    FoodSuggestion(name: 'Pasta Alfredo', caloriesPerUnit: 380),
    FoodSuggestion(name: 'Pasta Arrabbiata', caloriesPerUnit: 330),
    FoodSuggestion(name: 'Spaghetti Bolognese', caloriesPerUnit: 370),
    FoodSuggestion(name: 'Pizza Margherita Slice', caloriesPerUnit: 270),
    FoodSuggestion(name: 'Veg Pizza Slice', caloriesPerUnit: 285),
    FoodSuggestion(name: 'Cheese Pizza Slice', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Sushi (6 pcs)', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Sushi (12 pcs)', caloriesPerUnit: 400),
    FoodSuggestion(name: 'Falafel Wrap', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Shawarma Roll', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Burrito (Veg)', caloriesPerUnit: 320),
    FoodSuggestion(name: 'Burrito (Chicken)', caloriesPerUnit: 360),
    FoodSuggestion(name: 'Tomato Soup', caloriesPerUnit: 90),
    FoodSuggestion(name: 'Sweet Corn Soup', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Chicken Clear Soup', caloriesPerUnit: 80),
    FoodSuggestion(name: 'Vegetable Salad', caloriesPerUnit: 50),
    FoodSuggestion(name: 'Greek Salad', caloriesPerUnit: 160),
    FoodSuggestion(name: 'Sprout Salad', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Steamed Vegetables', caloriesPerUnit: 60),
    FoodSuggestion(name: 'Grilled Paneer', caloriesPerUnit: 230),
    FoodSuggestion(name: 'Grilled Fish', caloriesPerUnit: 200),

  ],
  'Beverage': [
    FoodSuggestion(name: 'Masala Chai', caloriesPerUnit: 72),
    FoodSuggestion(name: 'Ginger Tea', caloriesPerUnit: 45),
    FoodSuggestion(name: 'Cardamom Tea', caloriesPerUnit: 46),
    FoodSuggestion(name: 'Black Tea (No Sugar)', caloriesPerUnit: 2),
    FoodSuggestion(name: 'Green Tea (No Sugar)', caloriesPerUnit: 2),
    FoodSuggestion(name: 'Lemon Tea', caloriesPerUnit: 20),
    FoodSuggestion(name: 'Coffee (Black, No Sugar)', caloriesPerUnit: 2),
    FoodSuggestion(name: 'Coffee with Milk & Sugar', caloriesPerUnit: 60),
    FoodSuggestion(name: 'Cappuccino', caloriesPerUnit: 80),
    FoodSuggestion(name: 'Latte', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Espresso', caloriesPerUnit: 3),
    FoodSuggestion(name: 'Hot Chocolate', caloriesPerUnit: 190),
    FoodSuggestion(name: 'Filter Coffee (South Indian)', caloriesPerUnit: 80),
    FoodSuggestion(name: 'Cold Coffee', caloriesPerUnit: 150),
    FoodSuggestion(name: 'Iced Latte', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Iced Tea (Sweetened)', caloriesPerUnit: 90),
    FoodSuggestion(name: 'Iced Tea (Unsweetened)', caloriesPerUnit: 2),
    FoodSuggestion(name: 'Lassi (Sweet)', caloriesPerUnit: 180),
    FoodSuggestion(name: 'Lassi (Salted)', caloriesPerUnit: 120),
    FoodSuggestion(name: 'Buttermilk (Chaas)', caloriesPerUnit: 35),
    FoodSuggestion(name: 'Milkshake (Chocolate)', caloriesPerUnit: 350),
    FoodSuggestion(name: 'Milkshake (Strawberry)', caloriesPerUnit: 300),
    FoodSuggestion(name: 'Smoothie (Fruit)', caloriesPerUnit: 200),
    FoodSuggestion(name: 'Tender Coconut Water', caloriesPerUnit: 19),
    FoodSuggestion(name: 'Sugarcane Juice', caloriesPerUnit: 111),
    FoodSuggestion(name: 'Lemonade (Sweetened)', caloriesPerUnit: 99),
    FoodSuggestion(name: 'Lemonade (Unsweetened)', caloriesPerUnit: 20),
    FoodSuggestion(name: 'Fruit Juice (Orange)', caloriesPerUnit: 110),
    FoodSuggestion(name: 'Fruit Juice (Apple)', caloriesPerUnit: 114),

  ]
};